yearn/yearn-exporter

Dockerfile, docker-compose.yml, entrypoint.sh, grafana/provisioning/dashboards/boost_stats.json, grafana/provisioning/dashboards/curve_vaults_apy.json, grafana/provisioning/dashboards/dashboards.yml, grafana/provisioning/dashboards/share_price.json, grafana/provisioning/dashboards/tvl_vaults.json, grafana/provisioning/dashboards/up_time.json, grafana/provisioning/dashboards/v1_vaults.json, grafana/provisioning/dashboards/v2_vaults.json, grafana/provisioning/dashboards/ve_experimental_vaults.json, grafana/provisioning/datasources/datasources.yml, grafana/provisioning/notifiers/notifiers.yml, grafana/provisioning/plugins/plugins.yml, prometheus/prometheus.yml, readme.md, scripts/yearn.py, yearn/vaults_v2.py
Hey,
I've merged some code from:
https://github.com/DarkGhost7/yearn-exporter
and the dashboards from:
https://github.com/DarkGhost7/yearn-exporter-info/tree/master/Dashboards
and added a Dockerfile + docker-compose.yml so it can be run as part of a CI/CD pipeline.
Updated README with instructions how to run everything locally.
=> Dockerized setup of yearn-exporter + prometheus + grafana

grafana/provisioning/dashboards/earn_overview.json, grafana/provisioning/dashboards/ironbank_overview.json, grafana/provisioning/dashboards/v2_vaults.json
=> Updates for dashboards

docker-compose.yml, grafana/provisioning/dashboards/apy_overview.json, grafana/provisioning/dashboards/boost_stats.json, grafana/provisioning/dashboards/curve_vaults_apy.json
- added dashboards from https://github.com/yearn/yearn-exporter/pull/32
- setting the default dashboard to TVL
=> Feat/update dashboards from DarkGhosty

.gitignore, requirements.txt, scripts/tokenlist.py, yearn/api.py, yearn/ironbank.py, yearn/yearn.py
This implements `brownie run tokenlist` script which generates https://tokenlists.org/ compliant token list and saves it in `static/tokenlist.json`. This token list can later be accessed via web server.
=> yearn tokenlist

.gitignore, docker-compose.yml, entrypoint.sh, readme.md, services/tvl/docker-compose.yml
Adds `docker-compose.yml` to ease docker deployment of `historical_tvl` calculations.
=> feat: dockerize historical tvl

requirements.txt, scripts/apy.py, services/apy/docker-compose.yml, services/tvl/docker-compose.yml, yearn/apy/__init__.py, yearn/apy/common.py, yearn/apy/curve/rewards.py, yearn/apy/curve/simple.py, yearn/apy/special.py, yearn/apy/v1.py, yearn/apy/v2.py, yearn/entities.py, yearn/prices/curve.py, yearn/utils.py, yearn/v2/registry.py, yearn/v2/strategies.py, yearn/v2/vaults.py, yearn/yearn.py
- Harvests fetching for v2 strategies
- Simple v1 calculations
- Simple & Averaged v2 calculations
- Curve v1 & V2 calculations
=> feat: apy calculations

scripts/s3.py
Modifies the IPFS script to instead upload to S3
=> feat(apy): s3 upload

scripts/s3.py
=> feat: added vault migration info

yearn/partners/partners.py, yearn/partners/snapshot.py, yearn/utils.py, yearn/v2/registry.py
Add `WildcardWrapper` which matches any vault a wrapper deposited into.
=> feat(partners): add wildcard wrapper

scripts/s3_loanscan.py
- Improves vault filtering for loanscan endpoints, see: https://github.com/yearn/yearn-exporter/pull/103
- Exporter `s3_loanscan.py` performs same vault validation logic as before, but only for v2 registry
- Manually includes yveCRV-DAO aka Backscratcher from 'special' vaults
- Separates lend rate list reduction to new function def `get_formatted_lend_rates`
- Auto format with pylint fixes inconsistent white space
Loanscan API explorer 'app': https://loanscan.s3.us-east-1.amazonaws.com/index.html
Example vault export for yveCRV-DAO: https://loanscan.s3.us-east-1.amazonaws.com/yveCRV-DAO
Manifest (array of vault symbols for use as route parameters): https://loanscan.s3.us-east-1.amazonaws.com/manifest
All vault rates: https://loanscan.s3.us-east-1.amazonaws.com/all
=> fix: filters v2 and backscratcher vaults for loanscan [WEB-659]

yearn/partners/partners.py
add alchemix wrappers
- dai 0.4.3
- weth 0.4.2
=> feat(partners): add alchmix dai, weth wrappers

yearn/partners/partners.py
This PR adds Akropolis to Yearn Partners Registry
=> feat: adds akropolis to yearn partners

scripts/apy.py, yearn/prices/curve.py
EURT vault's apy was erroring (0x0d4EA8536F9A13e4FBa16042a46c30f092b06aA5)
=> fix: handled gauge from factory being zero address

readme.md
Changed MORALIS_TOKEN to MORALIS_KEY
=> chore: update wrong env variable

scripts/abracadabra_wrappers.py, yearn/partners/partners.py, yearn/partners/snapshot.py
revised https://github.com/yearn/yearn-exporter/pull/122
- add bentobox wrapper to support tracking cauldron balances
- add script to generate wrappers from cauldron addresses
- add abracadabra to partners
=> feat: add abracadabra partner

scripts/fantom_apy.py, scripts/s3.py, yearn/apy/curve/simple.py, yearn/curve.py, yearn/prices/curve.py, yearn/utils.py, yearn/v2/vaults.py
Will need the changes from this PR as well (https://github.com/yearn/yearn-exporter/pull/161) because it removes some seconds per block logic
=> feat: add ftm apy

scripts/apy.py, yearn/apy/v1.py, yearn/apy/v2.py
Address the request to use monthly apy instead of weekly apy when available as it is more stable
=> fix: prioritize monthly apy over weekly

yearn/prices/chainlink.py, yearn/prices/constants.py, yearn/prices/magic.py
added mapping from:
https://data.chain.link/fantom/mainnet
=> [EXP-26-226] add CL price feeds for fantom

.github/workflows/build-deploy.yaml, readme.md, scripts/s3.py
* Added GitHub action to build and push image to Elastic Container Repository.
* Changed how credentials are passed into boto so IAM credentials take effect in an AWS container automatically
=> [EXP-43-244] feat: Add GitHub action to build and upload container image

scripts/s3.py, yearn/v2/registry.py
initial thoughts for debugging the empty s3 exceptions
=> [EXP-53-253] feat: adding some more assertions and debug info.

yearn/prices/curve.py
Fixes [https://github.com/yearn/yearn-exporter/issues/263](https://github.com/yearn/yearn-exporter/issues/263)
=> [EXP-64-264] fix: remove pool from registry upon removal event

yearn/partners/partners.py
Adding our Vault as the WildcardWrapper
=> [EXP-93-293] Add Beethoven-X to partner

yearn/partners/partners.py
Adding CoFi smart contract to partner list
=> [EXP-101-301] Add CoFi to partner

yearn/partners/partners.py
=> [EXP-139-339] chore: update badger treasury address

scripts/s3.py
Delete telegram users from s3 script
=> fix: delete telegram users

scripts/historical_exporter.py, services/dashboard/docker-compose.yml
some fixes that were missed in #363
=> fix: arbitrum support

.github/workflows/partners.yaml, scripts/robowoofy/post_partners.py, yearn/partners/snapshot.py
This has been tested and the workflow works fine. There is one bug in the fantom price magic that is preventing a successful run on Fantom but thats unrelated to this workflow and can be resolved independently.
=> Partner gh action

yearn/v2/registry.py
- Update to new registry contract for Optimism
=> feat: update Optimism registry

yearn/prices/uniswap/v2.py
I catch the ValueError and return `None`, which will allow the price tool to proceed thru this error
Not much more to say on this one.
Check the codez
=> fix: uniswap ValueError

yearn/partners/partners.py
=> gearbox v2 vaults

yearn/prices/curve.py
I added a new `should_raise_err` kwarg to curve.get_balances that will prevent raising an error if set to `False`. Defaults to `True`
too simple to warrant explanation
try to price token yCRV 0xFCc5c47bE19d06BF83eB04298b026F81069ff65b at block 16136271 on Mainnet
=> fix: edge case - unable to fetch balances for spammy curve pools

requirements.txt
=> fix: bump ypm to 1.10.8

Makefile
=> feat: move network specific scripts one level up.

yearn/__init__.py
=> fix: network not connected race cndtn

scripts/s3.py
=> fix: using the new factory registry adapter and address provider

yearn/special.py
=> fix: use chain.height for special vault.

scripts/curve_apy_previews.py, scripts/s3.py, yearn/apy/common.py, yearn/v2/registry.py
=> feat: adding an error_reason when apy calculation fails for a vault

yearn/__init__.py, yearn/prices/curve.py
Fixed cEUR abi using ERC20 abi, modified curve pricing code to account for pools with 3 tokens
Explanation not necessary
magic.get_price(ceur)
=> fix: ceur PriceError

services/dashboard/docker-compose.infra.yml
=> feat: pin victoria-metrics docker image to v1.81.1

scripts/exporters/partners.py
Partner exporter was previously forward looking only since it used chain.height as start block. Now we set start to be the timestamp associated with the block before the one containing the first recorded partner tx depending on the chain to ensure all data is indexed for use
N/A
Made partner exporter bi-directional by setting start to a timestamp before the earliest recorded transaction on the specified chain. 
1. Conditionally initialize start var with fixed timestamp (found via querying partner_tx table in postgres db) for each network. This timestamp is associated with the earliest block containing a partner transaction on that specific network. 
2. Changed `start_block` in exporter config to use value from `closest_block_after_timestamp(start) - 1` …
=> feat: Make partner exporter bi-directional

grafana/provisioning/dashboards/strategists/Vault Overview.json
Updated to show the correct time view on the dashboard
=> fix(grafana): lockedprofitdegradation on vault overview

yearn/apy/staking_rewards.py
=> fix: check for vault

yearn/prices/compound.py
added flux comptroller to CompoundConfig list
copypasta
unit tests will run
=> feat: flux

yearn/prices/curve.py
=> add: crvusd plain pools to registry

yearn/prices/curve.py
=> fix(curve): new deployment of crvusd plain pools

yearn/prices/curve.py
=> fix(curve): third crvusd plain pool deployment

yearn/prices/curve.py
add the new curve factory from the registry
=> fix: add curve tricrypto factory

requirements.txt
=> fix: geth poa err from bedrock

yearn/prices/uniswap/v1.py
replaced a disk cache with a memory cache
=> fix: pickle error

Dockerfile
=> fix: install tk in containers for brownie console

yearn/prices/curve.py
Added handling for TricryptoPoolDeployed event in prices/curve.py
Followed the existing PoolAdded pattern
Run the trap
=> fix: curve tricrypto factory pools

yearn/apy/curve/simple.py, yearn/prices/uniswap/uniswap.py
cast the problematic number to Decimal before performing the math that was previously failing, and then cast back to float after the math
=> fix: OverflowError

services/dashboard/docker-compose.infra.yml
=> feat: pin docker images for grafana to 10.0.1 and postgres to 14

scripts/s3.py, yearn/apy/velo.py, yearn/v2/registry.py, yearn/v2/vaults.py
return zero apr if supply or rate or periodFinish are 0
=> fix(velo apy): add checks for zero supply, rate, or periodfinish

yearn/apy/v2.py, yearn/apy/velo.py, yearn/prices/magic.py
removed the broken import
backspace
yolo merge
=> fix: rebase conflict

requirements.txt
=> feat: velo support in ypm

yearn/apy/velo.py, yearn/v2/vaults.py
=> fix: add extra staking rewards apr for velo vaults

requirements.txt
=> feat: bumping sentry_sdk to 1.27.1

run.sh, services/dashboard/docker-compose.yml
=> feat: configure json-logger

.env.example, scripts/exporters/partners.py, scripts/exporters/sms.py, scripts/exporters/treasury.py, scripts/exporters/vaults.py, scripts/exporters/veyfi.py, scripts/exporters/wallets.py, yearn/constants.py
Made an env for CONCURRENCY as we discussed its best to leave this to user
=> feat: CONCURRENCY env

requirements.txt, services/dashboard/docker-compose.yml
=> Make it go

yearn/partners/snapshot.py
=> fix: reduce partners ram consumption

Makefile, run.sh, scripts/s3.py
tried to make the monitoring output more accurate
=> update: s3 monitoring to be more accurate

scripts/s3.py
=> fix: UnboundLocalError export_mode

requirements.txt
=> fix: use ypm commit from PR319

.gitignore, yearn/special.py
caught SSLError and raised ApyError so apy can complete
=> fix: pickle ssl err

requirements.txt
=> fix: price IB and others on opti

yearn/entities.py
=> fix: treasury txs memory leak

yearn/treasury/_setup.py
=> fix: arbitrum shitcoin exclusion

requirements.txt
=> feat: ypm version that supports base

requirements.txt
=> fix: various price errs

scripts/s3.py
=> fix: s3 mainnet after asynced load_streams

yearn/v2/vaults.py
=> fix: opti s3

yearn/apy/v2.py
adapted to new async reports, wasn't found during development due to irregular existing syntax
=> fix: async reports

scripts/exporters/transactions.py
=> fix: increase arbi transactions batch size

yearn/apy/staking_rewards.py
moved some things around so we can use the async version properly
=> fix: adapt staking pools to async events pr

yearn/outputs/describers/registry.py, yearn/outputs/describers/vault.py
Skipped fetching price for any token with no holders to prevent unnecessary and unimportant PriceErrors
=> fix: wallets on blocks with no hodlers

yearn/apy/staking_rewards.py
=> fix: staking rewards apy KeyError

yearn/v2/registry.py
=> fix: blockno check

scripts/s3.py
=> fix: 0 tvl when apy errs

scripts/abracadabra_wrappers.py, scripts/apy.py, scripts/exporters/transactions.py, scripts/exporters/wallets.py, scripts/historical_tvl.py, scripts/print_strategies.py, scripts/s3.py, scripts/s3_loanscan.py, scripts/tokenlist.py, scripts/tvl.py, tests/apy/test_convex.py, tests/yearn/v1/test_vault_v1.py, tests/yearn/v2/test_vault_v2.py, yearn/apy/curve/simple.py, yearn/apy/staking_rewards.py, yearn/apy/v2.py, yearn/apy/velo.py, yearn/partners/snapshot.py, yearn/special.py, yearn/treasury/accountant/ignore/vaults.py, yearn/treasury/accountant/revenue/fees.py, yearn/v1/vaults.py, yearn/v2/registry.py, yearn/v2/strategies.py, yearn/v2/vaults.py, yearn/yearn.py
This reverts commit 11d835e214fc96fe609b1327c5e4e0f57f605111.
=> Revert "Async load registry (#580)"

yearn/apy/curve/simple.py
Caught the JSONDecodeError and raised a descriptive ApyError
Run s3
=> fix: mainnet rpc err

Makefile, scripts/curve_apy_previews.py, scripts/revenues.py
add monitoring to curve apy previews
=> add: monitoring to scripts

requirements.txt
Unblocked some stuff in dank, treasury works much smoother now
=> fix: treasury-txs

yearn/constants.py
Added a new wallet to track for treasury
=> feat: add Stash contract to treasury wallets

scripts/partners_summary.py, scripts/utils/partners_cache_test.py, yearn/partners/snapshot.py
Got rid of a bunch of log spam in the partner containers, but kept it for partners_summary script
=> feat: make partner containers less verbose

CONTRIBUTING.md, services/dashboard/docker-compose.yml, yearn/_setup.py
added an env var to give users granular control over loggers if necessary
=> feat: LOGGER_LEVELS env var

yearn/helpers/exporter.py
=> feat: send it

requirements.txt
=> fix: thread/aio conflict

scripts/s3.py
=> fix: temp disable tg bot err msg

requirements.txt
=> fix: eth apy list iteration err

yearn/special.py
=> fix: SSLError

yearn/v2/registry.py
=> feat: add debug loggers

yearn/v2/registry.py
added 2 more loggers that were relevant to a bug on base branch
=> feat: more debug loggers

yearn/v2/registry.py
=> feat: autofetch release registry on all networks

requirements.txt, scripts/exporters/treasury_transactions.py, yearn/__init__.py, yearn/treasury/treasury.py
Made some upgrades in eth-portfolio that make subsequent runs much quicker
=> feat: e-p cache

requirements.txt
=> fix: reimplement ded curve pool fix

scripts/curve_apy_previews.py, scripts/s3.py
=> feat: upload APY and curve APY previews to multiple s3 endpoints

yearn/apy/curve/simple.py
=> fix: check for upstream proxy message

requirements.txt
=> fix: parse error on llama

brownie_init.sh
=> fix: only add base network config if it's missing.

scripts/s3.py
=> fix: temp fix for ERN related vaults which can't be priced on optimism

requirements.txt, scripts/s3.py, yearn/v2/registry.py
includes changes in ypricemagic for ERN (added ignore_pools arg):
https://github.com/BobTheBuidler/ypricemagic/tree/hotfix/ern
=> ERN pricing

requirements.txt
Added support for MakerDSR in eth_portfolio
=> feat: support maker dsr

yearn/yearn.py
=> fix: remove yeth from global yearn registry.

yearn/special.py
=> fix: wrap yfi price in float

yearn/v2/vaults.py
=> fix: wrap vault price in float

requirements.txt
=> fix: cache err when caching large prices

requirements.txt
Old dep version was missing an object we now use. Bumped version.
=> fix: missing import

grafana/provisioning/dashboards/yearn/yETH.json, scripts/exporters/yeth.py, yearn/apy/common.py, yearn/yeth.py
=> feat: calc swap volumes based on the current res

Makefile, requirements.txt, scripts/curve_apy_previews.py, scripts/drome_apy_previews.py, yearn/helpers/s3.py, yearn/helpers/telegram.py
add the previews apy scripts for aerodrome and velodrome new vaults creations
=> aero velo previews

scripts/accountant/sort.py, yearn/entities.py, yearn/treasury/_setup.py, yearn/treasury/accountant/expenses/__init__.py, yearn/treasury/accountant/expenses/people.py, yearn/treasury/accountant/expenses/security.py, yearn/treasury/accountant/ignore/__init__.py, yearn/treasury/accountant/ignore/maker.py, yearn/treasury/accountant/other_expenses/__init__.py, yearn/treasury/accountant/other_expenses/general.py, yearn/treasury/accountant/revenue/__init__.py, yearn/treasury/accountant/revenue/dinobots.py
=> feat: sort treasury stuff

requirements.txt
=> fix: uni v3 edge case price err

requirements.txt
removed 2nd instance of a kwarg
=> fix: bind db

yearn/ironbank.py
=> fix: ib Decimal TypeError

yearn/treasury/_setup.py
https://sentry.yearn.vision/organizations/yearn/issues/32626/?query=is%3Aunresolved&referrer=issue-stream&stream_index=2
=> fix: add hegic option token to shitcoins

yearn/v1/vaults.py
=> fix: Decimal type err

requirements.txt
Exclude the weird pool and others like it
=> fix: weird balancer v2 pool with no view methods

yearn/outputs/describers/vault.py, yearn/outputs/postgres/utils.py, yearn/prices/magic.py
=> fix: wallets Decimal err

yearn/prices/magic.py
=> fix: _get_price Decimal

requirements.txt
=> fix: 2 edge-y cases in ypm

yearn/v2/registry.py
=> fix: remove yvCurve-dETH-f from TEMP_REKT_VAULTS

yearn/apy/curve/simple.py
=> fix: turn Decimal prices to floats

yearn/prices/curve.py, yearn/special.py
=> Fix more decimal errs

requirements.txt, yearn/special.py
=> feat: override user-configured jsonrpc batch size for tenderly

yearn/v2/vaults.py
Reduced the log level of one logger to clean up these messages from sentry: https://sentry.yearn.vision/organizations/yearn/issues/32452/?environment=production&query=is%3Aunresolved&referrer=issue-stream&stream_index=2
=> chore: reduce log level

yearn/sentry.py
fixes https://sentry.yearn.vision/organizations/yearn/issues/30813/?environment=production&project=2&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=24
=> fix: transient 429 err at startup

yearn/outputs/postgres/utils.py
=> fix: reduce unnecessary math and result handling

yearn/iearn.py
=> fix: iearn decimal err

yearn/prices/curve.py
=> fix: moar decimal conversions

yearn/treasury/_setup.py
=> fix: skip uni v3 nft for now

yearn/apy/curve/simple.py
fixed a decimal/float maths error
=> fix: s3 mainnet Decimal err

requirements.txt
=> chore: bump ez-a-sync for better type hints and docs

yearn/events.py
=> chore: bump get_logs_asap concurrency

scripts/accountant/sort.py
=> chore: fmt

requirements.txt
=> feat: uniswap helper contract in ypm

services/dashboard/docker-compose.yml
=> feat: DANKMIDS_MAX_MULTICALL_SIZE env var

yearn/treasury/_setup.py
=> chore: add shitcoins to SHITCOINS

yearn/abis.py
=> fix: adapt to new ypm api

scripts/exporters/transactions.py
=> fix: BatchSizeError on base

scripts/s3.py
=> fix: BadRequest tg err

scripts/exporters/treasury_transactions.py
=> feat: filter 0 value transfers from treasury export

yearn/v2/vaults.py
=> feat: load strats in subthread to unblock loop

requirements.txt
=> fix: treasury txs block rewards

requirements.txt
=> fix: pin msgspec

yearn/apy/velo.py
=> fix: missing awawit

yearn/helpers/exporter.py
=> feat: has_data logger

yearn/__init__.py
=> fix: optimism

yearn/entities.py
=> feat(mypy): use pony stubs for ide typing

scripts/drome_apy_previews.py, yearn/apy/aero.py, yearn/apy/curve/rewards.py, yearn/apy/curve/simple.py, yearn/apy/staking_rewards.py, yearn/apy/velo.py, yearn/iearn.py, yearn/ironbank.py, yearn/prices/curve.py, yearn/special.py, yearn/v1/vaults.py, yearn/v2/registry.py, yearn/v2/vaults.py, yearn/yeth.py
=> chore: cleanup magic.get_price

scripts/apy.py, scripts/drome_apy_previews.py, scripts/exporters/transactions.py, scripts/gather.py, scripts/yteams.py, yearn/apy/staking_rewards.py, yearn/helpers/exporter.py, yearn/iearn.py, yearn/ironbank.py, yearn/multicall2.py, yearn/outputs/describers/registry.py, yearn/prices/balancer/v1.py, yearn/prices/uniswap/v2.py, yearn/prices/uniswap/v3.py, yearn/special.py, yearn/v1/registry.py, yearn/v1/vaults.py
=> feat: quick optimizations

yearn/treasury/accountant/classes.py
=> chore: cleanup logs during tx sortings

poetry.lock, pyproject.toml
=> chore: bump deps

poetry.lock, pyproject.toml, yearn/v2/vaults.py
=> fix: adapt to changes in multicall 0.11

Makefile, services/dashboard/docker-compose.yml
=> fix: adapt to recent docker/docker-compose changes

poetry.lock, pyproject.toml
=> fix: element vault reverts in ypricemagic

yearn/v2/vaults.py
=> chore: cleanup long tracebacks

yearn/v2/registry.py
=> fix: intermittent brownie network disconnections

yearn/outputs/victoria/victoria.py
=> chore: add type hints

yearn/treasury/_setup.py
=> chore: add shitcoin to shitcoins

yearn/treasury/treasury.py
=> fix: conflict with new checksum_dict

yearn/apy/curve/simple.py
=> fix: KeyError

scripts/exporters/treasury_transactions.py
=> chore: increase treasury txs exporter sleep interval

yearn/partners/snapshot.py
=> fix: hanging during v2 partner tx sorting

yearn/constants.py, yearn/treasury/accountant/prepare_db.py
=> feat: track vefarming multisig

yearn/entities.py, yearn/treasury/accountant/ignore/__init__.py, yearn/treasury/accountant/ignore/swaps/aave.py, yearn/treasury/accountant/ignore/swaps/compound.py, yearn/treasury/accountant/ignore/swaps/cowswap.py, yearn/treasury/accountant/ignore/swaps/curve.py, yearn/treasury/accountant/ignore/swaps/uniswap.py, yearn/treasury/accountant/ignore/vaults.py
=> chore: extract Token.scale_value helper

yearn/prices/curve.py
=> chore: refactor startup

poetry.lock, pyproject.toml
=> feat: use eth-portfolio from pypi

Dockerfile
=> feat: decode events in C
