yearn/yearn-exporter

- grafana/provisioning/dashboards/v1_vaults.json
- grafana/provisioning/dashboards/v2_vaults.json
This fixes the wrong names for v1 and v2 vault dashboards
> update vault names

- scripts/apy.py
- yearn/apy/v1.py
- yearn/apy/v2.py
Get this for the RAI vault now:
> fix: calculated apy using max of week ago and month ago apy [WEB-361]

- scripts/apy.py
We were using the alUSD vault by mistake
> fix: corrected lusd address in apy calculations

- yearn/apy/v1.py
- yearn/apy/v2.py
We were getting an imaginary number as the `apr_after_fees` for the gusd vault at `0xec0d8D3ED5477106c6D4ea27D90a60e594693C90` because `net_apy` was negative
`'gross_apr': (-0.852385187039765 + 3.093860710246853 j)`
I've changed `apr_after_fees` to be `net_apy` if this is the case, as we wouldn't be charging fees on a negative apy if I understand correctly
> fix: removed possibility of apr-after-fees being imaginary

- yearn/apy/common.py
- yearn/apy/curve/rewards.py
- yearn/apy/curve/simple.py
- yearn/apy/v2.py
The code was tested by
- Scraping https://api.yearn.finance/v1/chains/1/vaults/all for the past 15 days and data collected in 
[yearn_historical_apy.csv](https://github.com/yearn/yearn-exporter/files/6820340/yearn_historical_apy.csv)
- Running [script](https://gist.github.com/jainkunal/358e72c259e7dfda94a57689e4809b19) on the collected data and logging results in [validate.txt](https://github.com/yearn/yearn-exporter/files/6820351/validate.txt)
Usually the `net_apy` is <1% which was expected but at times, it does go as high as 40% which couldn't be explained.
> feat(apy): add ability to specify block for calculations

- scripts/s3_loanscan.py
- "Forks" `scripts/s3.py` to `scripts/s3_loanscan.py` and retools the script for loanscan.io
- For every vault in v1 registry, v2 registry, yve-crv jar, and backscratcher:
- filter out vaults with missing or non-truthy `is_endorsed` flag
- filter out non-migrated vaults, i.e. vaults where current vault address does not match most recent migration address
- create JSON object for loanscan schema. Where apy type is `crv`, expect multiple tokens in `lendRates` array:
```
{
"lendRates": [{
"apr": 0.00, // ((vault.apy(samples).net_apy + 1)**(1/365) - 1) * 365
"apy": 0.00, // vault.apy(samples).net_apy
"tokenSymbol": "ySYMBOL"
}, { ... }]
}
```
- Ensures paths `{project root}/generated` and `{project root}/generated/loanscan` exist. Removes previous files from `{project …
> feat: export loanscan data to s3 [WEB-659]

- yearn/ironbank.py
- yearn/prices/magic.py
Added a new `magic#get_price_safe` which always returns the price or 0 and use that in the ironbank calculations.
> fix(ironbank): unknown tokens shouldn't crash the exporter

- yearn/prices/coingecko.py
- yearn/prices/magic.py
Adds ability to fetch instant prices from coingecko. If a block other than `None` is used to fetch prices, the call will return `None`.
> fix(prices): use coingecko for non historical prices

- scripts/apy.py
- yearn/apy/curve/simple.py
Gauges that have been created recently do not have a `controller` property e.g. https://etherscan.io/address/0xd8b712d29381748dB89c36BCa0138d7c75866ddF. Default to `0x2F50D538606Fa9EDD2B11E2446BEb18C9D5846bB` if this is the case
> fix: handled case where there is no controller on a gauge

- grafana/provisioning/dashboards/system/exporters_duration.json
- requirements.txt
- scripts/exporter.py
- scripts/historical_exporter.py
- services/dashboard/docker-compose.yml
- yearn/config.py
- yearn/outputs/victoria.py
- yearn/v2/registry.py
- yearn/v2/strategies.py
- yearn/v2/vaults.py
- yearn/yearn.py
With this PR I've implemented parallel computing for the historical exporter which speeds up the exports by a factor of `POOL_SIZE` .
The intervals that must be exported are chunked by `CHUNK_SIZE` and each chunk is passed to the worker.
In order to circumvent pickling of the yearn object, I had to re-initialize it in every `#export_chunk` invocation.
This makes it a bit slower by a constant time per chunk but it's acceptable imo.
I assumed a quite realistic memory footprint of `8GB` per worker and scale it up once at startup to the available ressources.
So if you have 20GB free memory it will allocate a joblib pool with 2 workers running in separate processes. The amount of workers can be overriden with the env variable `POOL_SIZE` but a too high value will cause memory to bloat up very …
> Parallelization of historical exporter

- scripts/s3.py
so it can still be a valid telegram message
> fix: cap apy error message length

- scripts/apy.py
- tests/prices/test_curve.py
- yearn/prices/curve.py
Fixes https://github.com/yearn/yearn-exporter/issues/187
Check to see if the 'CryptoSwap' registry can be used before falling back to the original registry
The crypto swap registry can be found at position 5 in the address provider
> fix: use crypto swap registry if available

- yearn/apy/curve/simple.py
We were calculating rKP3R discount incorrectly. Instead of using the `rKP3R.discount()` as the percentage that rKP3R discounted KP3R redemption price, we should actually be using `100 - rKP3R.discount()`, since the `discount` represents the percentage of the real price that strike price is. At 50%, this didn't matter, so it was correct either way, but on the shift to 90%, it became incorrect. 
In the past, CVX and CRV made up the vast majority of the APR for these vaults, so it wasn't clear that something was wrong. But with KP3R's recent moon and CVX and CRV crashing, the difference became noticeable.
> [WEB-1259-203] fix: correct calculation of discounted rKP3R price

- yearn/exceptions.py
- yearn/multicall2.py
- yearn/outputs/describers/vault.py
- yearn/prices/yearn.py
* feat: multicall can require success
* fix: yearn oracle error for zero share price
* feat: add gusd incident handling
> [EXP-14-216] fix: oracle regression

- yearn/apy/curve/rewards.py
check that the staking rewards contract has a reward token, otherwise set the reward apy to 0
> [EXP-30-230] fix: check for reward token

- tests/prices/test_curve.py
- yearn/events.py
- yearn/prices/curve.py
- yearn/prices/magic.py
- yearn/sentry.py
* add support for curve v5 factory (fixes #213)
* build lp token to pool mapping on load (`get_lp_token`, `get_token`)
* add cached mappings from registries/factories to pools
* add address provider ids enum for readability
* watch for curve registry updates
* watch for new registries deployed
* remove and generalize cryptoswap registry logic
* deprecate `registry` in favor of `get_registry(pool)`
* change `metapools_by_factory` to cached `factories`
* convert token and pool args to checksum address
* add `read_pool` utility to fetch pool_list/pool_count type registries commonly found in curve
* vastly simplify logic around factory and registry api
> [EXP-33-234] refactor: curve oracle and curve v5 support

- services/dashboard/docker-compose.yml
- services/ipfs/docker-compose.yml
- services/tvl/docker-compose.yml
- yearn/sentry.py
We can activate now sentry release tracking by passing a `SENTRY_RELEASE` env like so:
`export SENTRY_RELEASE=$(git rev-parse --short HEAD)`\
[https://docs.sentry.io/product/releases/](https://docs.sentry.io/product/releases/)
if this is set to a value sentry will show it under the Releases section which can be further filtered by the environment.
The environment (previously `ENV`) has been replaced in favor of sentry's default `SENTRY_ENVIRONMENT`\
[https://docs.sentry.io/platforms/python/configuration/options/#common-options](https://docs.sentry.io/platforms/python/configuration/options/#common-options)
Also changed some custom tags like discussed with Bob.
> [EXP-35-236] sentry release tracking + custom tags

- .gitignore
- scripts/s3.py
- yearn/graphite.py
You can test by signing up for a free account here:
https://grafana.com/auth/sign-up/create-user?plcmt=sub-nav
Pass the following environment variables:
* GRAFANA_URL 
* GRAFANA_API_KEY
For example:
```bash
docker build -t yearn-exporter:dev .
docker run -e NETWORK="ftm-main" -e EXPLORER="https://api.ftmscan.com/api" -e WEB3_PROVIDER="<FTM WEB3 PROVIDER>" -e FTMSCAN_TOKEN="<FTMSCAN TOKEN>" -e GRAFANA_API_KEY="<ID>:<PASSWORD>" -e GRAFANA_URL="<YOUR GRAPHITE URL>" yearn-exporter:dev s3
```
> [EXP-45-246] Submit graphite metric when the s3.py script runs successfully

- scripts/s3.py
- yearn/exceptions.py
Sometimes S3 script generates empty files which overwrites the data in the S3 bucket and effectively brings down the API used to populate the APY on the website.\
This pull request adds a simple check before S3 upload is done to prevent above situation.
> [EXP-48-248] feat: added exception to abort S3 upload on empty file

- yearn/apy/curve/simple.py
- yearn/v2/vaults.py
Still need to look into whether we can calculate curve apys in the same method we use as on mainnet for other chains, but we could think about just excluding all curve apy calcs for non-mainnet chains and just use average apy calcs
> [EXP-60-260] fix: use average apy calculations for curve tricrypto vault

- yearn/partners/partners.py
Adds the newly deployed Shapeshift DAO Router (0x90a48d5cf7343b08da12e067680b4c6dbfe551be) to the partners list.
Our router is loosely based on the examples provided by Yearn and call's the vault deposit method directly passing the vault tokens to the recipient that is not our contract.
```
vault.deposit(amount, recipient);
```
Is there an easy way to confirm the WildCardWrapper will be functional with this implementation?
Thank you!
> [WEB-1139-193] adds Shapeshift DAO router

- yearn/prices/magic.py
- yearn/special.py
Using the full path to import yearn.apy.common objects resolves the circular import error when brownie apy commands are run.
> [EXP-70-270] fix: full path imports fixes circular import

- yearn/apy/v2.py
- yearn/v2/vaults.py
There's a problem with yvBoost where there are only two harvests, but the vault is very old, so the inception block is inaccurate.
Instead record the apy inception point as the first harvest - when assets have been deposited by the vault into a strategy and they start earning yield.
> [EXP-73-273] fix: record apy inception point from first harvest

- scripts/apy.py
- yearn/apy/curve/simple.py
- yearn/prices/curve.py
In calculating vault apy, the liquidity gauge contract is required.  Generally this address is found in either the `factory` or `registry`, whichever has a `get_gauge` method.  `Eurt`, is unique in that it has both a `factory` and a `registry` with the `get_gauge` method.  The current implementation will return `contract(factory).get_gauge(pool)` if it's not the `ZERO_ADDRESS` or None.  The gauge address for `Eurt` is found in the `registry` contract but it is never reached b/c the if statement is taken as opposed to the elif shown below.  If we add the additional constraint that `contract(factory).get_gauge(pool)` must also be not the `ZERO_ADDRESS` we can accomodate the `Eurt` edge case.
Additional changes: deleted unnecessary whitespace (editor setting) and removed duplicate apy …
> [EXP-74-274] Fix/eurt vault apy

- scripts/apy.py
- yearn/apy/v2.py
For Fantom, prioritize the weekly apy over the monthly. The APYs on Fantom vary quickly and harvests are more frequent than on mainnet, where infrequent harvests mean showing the weekly APY results in misleading spikes
> [EXP-83-283] fix: use weekly apys for fantom

- yearn/exceptions.py
- yearn/utils.py
With an unsynced node, chain.height will return zero, which causes an incorrect value of None to be returned.
This will raise an exception notifying the user to check on their node.
> [EXP-87-287] fix: raise useful exception on contract creation block edge case

- requirements.txt
- services/dashboard/docker-compose.test.yml
- tests.sh
- tests/apy/curve_simple_apy.feature
- tests/apy/test_apy.py
- tests/apy/test_convex.py
- yearn/apy/curve/simple.py
* Ensure strategies are in the correct order - curve first, then convex
* Correct price calculation for `rKP3R`
* Handle some strategies using `id` instead of `pid`
* Handle some strategies using `localKeepCRV` rather than `KeepCRV`
> [EXP-84-284] fix: more convex fixes

- yearn/apy/curve/simple.py
Before the code assumed that the performance fee of the strategy was equal to the performance fee from the vault, so total performance fee = 2 \* vault performance fee. This led to incorrectly low apys.
However with the recent changes to all performance fees being handled by the vault, and not the strategy, this assumption is no longer valid.
> [EXP-103-303] fix: remove assumption that strategy performance fee is equal to vaults

- scripts/apy.py
- yearn/v2/vaults.py
It's a curve vault but curve vault apy calculations are not supported on anything other than mainnet, fallback to defaults pps apy calculations
> [EXP-105-305] fix: exclude mim-3pool fantom vault from apy calculations

- yearn/utils.py
Needs a lot more testing for any unwanted side-effects.\
Especially `pcMap`, `ast` and  `coverageMap` are the biggest memory consumers.
> [EXP-102-302] feat: removing some internal brownie contract data to reduce the memory footprint

- yearn/partners/partners.py
adds popcorn's BTR contract which holds 4 vault tokens
> [EXP-104-304] update partners.py

- .github/workflows/tests._fullsuite.yaml
- .github/workflows/tests.partners.on_pull_req.yaml
- .github/workflows/tests.partners.on_push.yaml
- requirements.txt
eth_retry was extended to retry on requests.exceptions.ConnectionError in addition to the regular ConnectionError. This is necessary per the failed tests on minor-fixes branch and will eliminate similar failures in the future.
> [EXP-111-311] chore: bump eth_retry version

- scripts/apy.py
- yearn/apy/curve/simple.py
net apy can not be negative for vaults with version > 0.3.5, which all convex vaults should be anyway
> [EXP-112-312] fix: correct negative cvx vault net apy

- yearn/v2/vaults.py
Can't use the curve apy calculations on non-mainnet chains. Maybe we should exclude non-mainnet vaults from them by default.
> [EXP-118-318] fix: exclude mim-3pool vault from curve apy calculations

- yearn/v2/vaults.py
net apy is 1.2048184716443852e+21 which is correct when cross referencing with convex's apr, however something with curve's pool apr must be incorrect. This PR defaults back to pps apy calculations, since there aren't any harvests an apy value will not be provided. The vault has never been deposited into anyway since it was deployed about a year ago so this data isn't needed anyway.
[https://etherscan.io/address/0x3D27705c64213A5DcD9D26880c1BcFa72d5b6B0E](https://etherscan.io/address/0x3D27705c64213A5DcD9D26880c1BcFa72d5b6B0E)
> [EXP-117-317] fix: exclude curve usdk vault from curve apy calculations

- yearn/apy/v2.py
Was getting a division by 0 error for this vault - https://etherscan.io/address/0xD4108Bb1185A5c30eA3f4264Fd7783473018Ce17, which has a total performance fee of 100%, and 0% management fee
> [EXP-116-316] fix: check for division by zero when calculating gross apr

- services/dashboard/docker-compose.yml
- yearn/logs.py
- yearn/prices/balancer/balancer.py
- yearn/prices/balancer/v1.py
- yearn/prices/balancer/v2.py
- yearn/prices/magic.py
- yearn/treasury/buckets.py
Added functionality for discovering prices for:
> balancer v2 pools and some more price discovery fixes

- grafana/provisioning/dashboards/yearn/Overview.json
- lower the limit on the filter for a view from 1b to 10k usd
> fix: grafana dashboard overview

- Makefile
- scripts/partners_exporter.py
- services/dashboard/docker-compose.yml
- yearn/outputs/victoria/output_treasury.py
- yearn/partners/snapshot.py
- yearn/treasury/treasury.py
Aims to split the partners-related processing to a new container named partners-exporter,
to solve the data race issue caused by #349.
> fix: move the partner processing to a new container

- yearn/partners/partners.py
The rhino.fi L2 StarkEx bridge contract contains all yearn vaults that are bought by users via rhino.fi Invest section
> Include rhino.fi to partners.py

- Makefile
- scripts/revenues.py
- services/dashboard/docker-compose.yml
In order to test without uploading to s3 you can try: `DEBUG=true make revenues`
This will dump the result data to stdout.
By default the script sets the first of month as `from` and the current date as `to` for the range query.
You can override it by passing `REVENUES_FROM` or `REVENUES_TO` env variables.
> feat: adding a basic revenue script that publishes revenue data to s3

- yearn/apy/common.py
- yearn/prices/uniswap/uniswap.py
can be tested with:
`DEBUG=true make apy network=arbitrum`
> fix: guard usage of chainlink feeds per network

- interfaces/yearn/partner_tracker_arbitrum.json
- yearn/__init__.py
- yearn/partners/delegated.py
frist, remove the middleware cache:
```
docker volume rm arbitrum_cache
```
start a brownie console:
```
make console network=arbitrum
```
verify the contract can be loaded
```
>>> from yearn.partners import delegated
>>> Contract('0x0e5b46E4b2a05fd53F5a4cD974eb98a9a613bcb7')
<YearnPartnerTracker Contract '0x0e5b46E4b2a05fd53F5a4cD974eb98a9a613bcb7'>
```
> fix: read partner tracker for arbi from interface abi.

- yearn/prices/magic.py
- yearn/v2/strategies.py
- yearn/v2/vaults.py
this pr fixes:
- renBTC prices not being stable before 2020-10-10
- broken event parsing for vaults and strategies
deployed to staging with a full historical rebuild
> Fixes for renBTC (mainnet) and event parsing for vaults/strategies

- services/dashboard/docker-compose.yml
minor update for docker-compose v2
> fix: use dashes for docker-compose v2 default container names

- run.sh
(e.g. `brownie run s3 with_monitoring`)
> fix: regex to create a NAME for running multiple command args 

- requirements.txt
Added `wait_for_block_if_needed` kwarg to closest_block_after_timestamp in ypm, and updated the dependency here.
^^
Run the debug apy script
> fix: closest_block_after_timestamp signature

- yearn/outputs/postgres/utils.py
https://sentry.yearn.vision/organizations/yearn/issues/7626/?environment=production&project=2&query=is%3Aunresolved
Added gas token name and symbol for Arbi and Opti
its just a key lookup so I added the vals
check the chain bro
> fix: cache_token defaults for Arbi and Opti

- scripts/exporters/treasury_transactions.py
- yearn/prices/curve.py
This PR fixes the pricing of the yCRV token [0xFCc5c47bE19d06BF83eB04298b026F81069ff65b](https://etherscan.io/token/0xfcc5c47be19d06bf83eb04298b026f81069ff65b)
I've fixed the bug where we couldn't price the underlying token of a factory pool.
I've modified the pricing logic inside `curve.get_coin_price` so that we allow the token to be in >1 pools. If so, we determine the pool with the deepest liquidity and use it.
I've deployed this to yv-staging, open to verification.
> fix: curve pool underlying prices

- tests/yearn/treasury/test_buckets.py
- yearn/treasury/buckets.py
Some newer balancer pools reference itself in the list of underlying tokens. We simply ignore that specific underlying in our get_token_bucket code if the address matches the pool address
See above
Call get_token_bucket on 0x2F4eb100552ef93840d5aDC30560E5513DFfFACb on mainnet
> fix: recursion error

- requirements.txt
> fix: locking python-telegram-bot to 13.15

- Makefile
- scripts/curve_apy_previews.py
- yearn/apy/curve/simple.py
I've added a new exporter for calculating APY previews for curve gauges which are not yet linked to a vault.
I'm fetching all available gauges from the curve API and publishing the resulting apys to a s3 bucket.
Refactored the curve simple code so it could be called without a vault but by passing the gauge values as params.
> feat: adding a apy preview exporter for curve factories.

- scripts/s3.py
- yearn/apy/__init__.py
- yearn/apy/common.py
- yearn/apy/v1.py
- yearn/apy/v2.py
- yearn/special.py
#435 
Added the block nums for `now`, `week_ago`, `month_ago`, `inception` to all apy calculators where we return also `ApyPoints`
For those where we don't return them like e.g. curve simple I didn't add this info yet because it's hard to determine which block it should be attributed to with the current calc logic.
use a network which calculates quickly, e.g. ftm:
`DEBUG=true make apy network=ftm`
this produces the folllowing output for `yvWFTM`:
```
{
"inception": 16476356,
"address": "0x0DEC85e74A92c52b7F708c4B10207D9560CEFaf0",
"symbol": "yvWFTM",
"name": "yvWFTM 0.4.3",
...
},
"apy": {
...
"points": {
"week_ago": 0.04074685763155883,
"month_ago": 0.05048203850688959,
"inception": 0.3656106019359633
},
"blocks": {
"now": 52276022,
"week_ago": 51955878, …
```
> feat: include a new object with block nums for a few APY sample points

- yearn/outputs/postgres/utils.py
- yearn/utils.py
converting the HexString returned from the `name()` and `symbol()` functions from the MKR contract to normal strings that we can cache in our db.
https://etherscan.io/address/0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2#readContract
> fix(treasury_transactions): decode bytes32 responses into strings

- yearn/v2/registry.py
Adds the releaseRegistry which released `0.4.6` vaults. 
```python
>>> from yearn.v2.registry import Registry
>>> r = Registry()
>>> r.releases
{
'0.2.2': 0xBFa4D8AA6d8a379aBFe7793399D3DdaCC5bBECBB,
'0.3.0': 0xe11ba472F74869176652C35D30dB89854b5ae84D,
'0.3.1': 0xcB550A6D4C8e3517A939BC79d0c7093eb7cF56B5,
'0.3.2': 0x986b4AFF588a109c09B50A03f42E4110E29D353F,
'0.3.3': 0x662fBF2c1E4b04342EeBA6371ec1C7420042B86F,
'0.3.4': 0x34fe2a45D8df28459d7705F37eD13d7aE4382009,
'0.3.5': 0xA696a63cc78DfFa1a63E9E50587C197387FF6C7E,
'0.4.0': 0xE7bf2905371cfEAEefE2D4c2C386b6B2a7e4270a,
'0.4.1': 0x090c9d94817e78Cd975034B1be596bf432E1f6C6,
'0.4.2': 0x671a912C10bba0CFA74Cfc2d6Fba9BA1ed9530B2,
'0.4.3': 0x9C13e225AE007731caA49Fd17A41379ab1a489F4,
'0.4.5': …
```
> fix: adding releaseRegistry to the list of known registries.

- yearn/prices/curve.py
#469 - only addresses the first of 3 tasks
Fixed a bug that involved zipping 2 iterables of different sizes which caused the PriceError
Filtered one of the iterables in a different location in the code to prevent the zip issue.
Just try to fetch price
> fix: sdCRV PriceError

- scripts/curve_apy_previews.py
Fixed an issue that limited display of pool tokens to 2 tokens
Fixed an intermittent issue with failed calls to Curve's API
For the former, I increased the int in a range() call
For the latter, I implemented a retry loop.
run curve_apy_preview
> Fix curve api preview

- yearn/prices/curve.py
Fixed a bug when calculating the curve pool price and one of the pool coins is naked ETH (thanks @BobTheBuidler )
`magic.get_price('0x9848482da3Ee3076165ce6497eDA906E66bB85C5')`
> fix: don't try to handle naked ETH as a contract

- yearn/utils.py
Without merging abis, we only get the implementation and lack any valid methods/events from the proxy itself.
When querying a proxy, include the abi from both the proxy and the implemenation contract.
`abi = abi1 + abi2`
Can test against this proxy `0xE95A203B1a91a908F9B9CE46459d101078c2c3cb` and it's implementation: `0xE95A203B1a91a908F9B9CE46459d101078c2c3cb`
> feat: merge proxy and implementation abis

- scripts/s3.py
- services/dashboard/docker-compose.yml
- yearn/prices/uniswap/uniswap.py
moved the `tvl` calculation up into the `try..except` block so a single tvl failure doesn't crash the entire script.
> fix(apy): tvl calculation crash

- tests/prices/test_synthetix.py
- yearn/prices/synthetix.py
Added the Synthetix ExchangeRate contract address for optimism
Simple addition to a mapping
Try to price sETH on Opti
> fix: sETH pricing on optimism

- yearn/apy/v2.py
Currently only ftm vaults are showing weekly apy.
Now all networks besides ETH for v2: avg will show weekly apys for all non-eth chains not just ftm.
> feat: set arbi and opti to weekly apy

- yearn/v2/registry.py
- Update the staking rewards registry address to latest
- Replaced current address where its being used
- Using https://github.com/yearn/yearn-strategies/issues/475#issuecomment-1495139236
> fix(optimism): update staking rewards registry address

- yearn/partners/partners.py
Move SpoolFi to eth network
`make partners-summary-eth`
> partner: update spoolfi to eth

- yearn/__init__.py
- yearn/prices/uniswap/v3.py
fixes https://github.com/yearn/yearn-infra/issues/54
Added another check for balance and creating the UST TokenBridge contract with the `ERC20` interface so it includes the `decimals()` function.
> fix: uniswapv3 balance

- yearn/apy/staking_rewards.py
> fix: early exit if staking pool still has totalSupply == 0

- scripts/load_streams.py
- yearn/entities.py
- yearn/utils.py
Reduced runtime for load_streams from a few hours to a few minutes
The usual methods
`brownie run load_streams` with the proper envs set
> feat: asyncify load streams script

- yearn/partners/snapshot.py
Swapped out AsyncThreadPoolExecutor with concurrent.futures.ThreadPoolExecutor since we actually do want to use it in sync context here
n/a
`make partners`
> fix: partners

- requirements.txt
> fix: pin dep

- scripts/curve_apy_previews.py
- scripts/s3.py
> fix: ApyError string formation when Exc args are not strings

- Dockerfile
https://github.com/yaml/pyyaml/issues/601
Resolved a conflict between cython and the pyyaml version required by brownie
Added a build step to the dockerfile
make build
> fix: build step bug due to pyyaml cython interaction

- yearn/partners/snapshot.py
I added a semaphore to ensure that with COONCURRENCY>1, the partners db still maintains its integrity
> fix: ensure partner db validity with concurrency>1

- requirements.txt
https://github.com/BobTheBuidler/ypricemagic/pull/318
> fix: don't price alETH with uni_v3

- yearn/apy/common.py
- yearn/apy/velo.py
adding keepVELO info to exporter so it can be more easily accessed by the FE for displaying fees, similar to keepCRV
> feat: add keep_velo to fees for ui usage

- yearn/apy/curve/simple.py
Added a ApyError as a fallback to catch errs and allow debuggable outputs
> fix: curve apy breaks s3 when pool is None

- yearn/v1/vaults.py
- yearn/v2/vaults.py
Handled a potential UnboundLocalError after a PriceError to save us some future debug trouble
> fix: Handle price failure case

- yearn/treasury/accountant/accountant.py
After each tx is sorted, the events cache is popped
> feat: further reduce treasury-txs memory use

- services/dashboard/docker-compose.yml
ypm has a disk cache for certain objects now. This PR shares the disk cache across containers on the same network.
> feat: shared ypm cache

- yearn/v2/registry.py
If the release registry on a particular registry was ever updated, the exporters did not know to query the old one(s). This PR fixes that.
> fix: query past and present Release Registry

- yearn/v2/strategies.py
swapped out y get_logs_asap which should only be used in main thread with yearn get_logs_asap which will work until we dethread the startup sequence
> fix: thread async conflict

- yearn/apy/__init__.py
- yearn/apy/aero.py
- yearn/apy/velo.py
- yearn/v2/vaults.py
added fwd looking apys for aerodrome fork of velodrome 
copy velo apys
https://www.diffchecker.com/3bwDxzuZ/
- [-] I have included any relevant documentation for the repo maintainers
- [-] (If fixing a bug) I have added a test to the test suite to test for this particular bug
> feat: add aerodrome fwd-looking apys

- requirements.txt
curve object is not a valid object on Base chain, which created an AttributeError when sorting token buckets. 
This fixes that.
Added a boolean check
> fix: balance buckets on base

- scripts/exporters/wallets.py
Added network param to wallets exporter's data_query
Added network param to wallets exporter's data_query
run wallets exporter on previously "full" db, watch new blocks magically appear
> fix: wallets exporter data_query not chain-aware

- requirements.txt
made dank support tenderly and made eth_retry retry on alchemy.io rate limit errs
> feat: make compatible with more NaaS rpcs

- requirements.txt
added proper type checking to a few a_sync utils so mypy works correctly
> feat: proper type checking for ez-a-sync functions

- requirements.txt
https://sentry.yearn.vision/organizations/yearn/issues/32473/?environment=production&query=is%3Aunresolved+script%3Ayeth_exporter&referrer=issue-stream&statsPeriod=14d&stream_index=2
removed a deprecated init arg
> fix: ClientResponseError wrapper case

- requirements.txt
fixed the last case where a rate-limited response causes failure
> fix: decorate _get_logs_async_no_cache with eth_retry

- yearn/iearn.py
- yearn/prices/curve.py
Swap out contract for Contract, both are lru_cached but Contract for each of these contracts will be inited during ypm initialization so it makes no sense to load both for each curve pool / iearn token
YOLO merged on sunday so prod can defeat the rate limits easier
> feat: 1200 less getCode calls @ startup

- .env.example
- Makefile
- readme.md
- scripts/utils/debug-price.py
Related issue # (if applicable): adds in the ypm debugger script to utils and a make file to use it, set env `BAD` and optionally `BLOCK` .
> feat: add ypm_debug script

- yearn/sentry.py
We will now raise AttributeErrors instead of bypassing them like we do for other exceptions
This will mitigate https://sentry.yearn.vision/organizations/yearn/issues/33164/?environment=production&query=is%3Aunresolved&referrer=issue-stream&stream_index=0 and ensure containers reboot properly
> fix: raise AttributeError

- scripts/s3.py
Unsure if this will fix the issue entirely but since we're using assetsDynamic but only ever passing in a 1-address array, I'm trying assetDynamic instead and hoping this will fix the reverting issue
I can't reproduce the issue with either method so... yolo
> fix: s3 revert on opti

- requirements.txt
all changes can be found in dank_mids.brownie_patch
> feat: steep Contract memory usage reduction

- scripts/exporters/wallets.py
- yearn/helpers/snapshots.py
- yearn/outputs/victoria/victoria.py
- yearn/partners/snapshot.py
- yearn/prices/magic.py
- yearn/prices/uniswap/v2.py
- yearn/treasury/accountant/__init__.py
- yearn/treasury/accountant/classes.py
> chore: fmt f-strings lazily

- yearn/yeth.py
> feat: asyncify yeth

- scripts/exporters/treasury_transactions.py
> fix: deduplicate internal transfers in db

- services/dashboard/docker-compose.infra.yml
- services/dashboard/docker-compose.test.yml
- services/dashboard/docker-compose.yml
Removed it per instructions in the warning
> fix: deprecated `version` field in docker-compose files
